name: Real Estate CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /mnt/newvolume/real-estate
            git pull origin main
            docker compose down
            docker compose up -d --build
